# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/Admin/Desktop/wang/7020/28_eth_udp_loop/prj/eth_udp_loop.srcs/sources_1/ip/sync_fifo_2048x8b/sync_fifo_2048x8b.xci
# IP: The module: 'sync_fifo_2048x8b' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Admin/Desktop/wang/7020/28_eth_udp_loop/prj/eth_udp_loop.gen/sources_1/ip/sync_fifo_2048x8b/sync_fifo_2048x8b.xdc
# XDC: The top module name and the constraint reference have the same name: 'sync_fifo_2048x8b'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/Admin/Desktop/wang/7020/28_eth_udp_loop/prj/eth_udp_loop.gen/sources_1/ip/sync_fifo_2048x8b/sync_fifo_2048x8b_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'sync_fifo_2048x8b'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/Admin/Desktop/wang/7020/28_eth_udp_loop/prj/eth_udp_loop.gen/sources_1/ip/sync_fifo_2048x8b/sync_fifo_2048x8b_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'sync_fifo_2048x8b'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Users/Admin/Desktop/wang/7020/28_eth_udp_loop/prj/eth_udp_loop.srcs/sources_1/ip/sync_fifo_2048x8b/sync_fifo_2048x8b.xci
# IP: The module: 'sync_fifo_2048x8b' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Admin/Desktop/wang/7020/28_eth_udp_loop/prj/eth_udp_loop.gen/sources_1/ip/sync_fifo_2048x8b/sync_fifo_2048x8b.xdc
# XDC: The top module name and the constraint reference have the same name: 'sync_fifo_2048x8b'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/Admin/Desktop/wang/7020/28_eth_udp_loop/prj/eth_udp_loop.gen/sources_1/ip/sync_fifo_2048x8b/sync_fifo_2048x8b_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'sync_fifo_2048x8b'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/Admin/Desktop/wang/7020/28_eth_udp_loop/prj/eth_udp_loop.gen/sources_1/ip/sync_fifo_2048x8b/sync_fifo_2048x8b_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'sync_fifo_2048x8b'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
